### ISSUE TITLE
Checking makefile

### ISSUE THREAD

**Issue by kuolu** [gordon-cs/Simulation-of-Metallic-Glass#46]
Hi Dr. Senning,

I try to compile [makefile](https://github.com/gordon-cs/Simulation-of-Metallic-Glass/blob/master/server/Makefile) however it keeps giving me errors. Please take a look if you have time.

Thank you

-Kuo

P.S. I'm using vscode (an editor) to write makefile and somehow it writes a tab as two spaces, so the compiler keeps giving me " no proper separation " error for 2 days LOL.

**Comment by kuolu** [comment]
I figured it out and it's working now... It's just that i need to change "TARGET = bin" TO "TARGETDIR = bin"

**Comment by jsenning** [comment]
Kuo,
    
    Sorry -- it's been a busy day today.  I'm glad you got it figured
    out!
    
    Prof. Senning
    
    On 02/14/2017 03:16 PM, Kuo Lu wrote:
    
    
      
      I figured it out and it's working now... It's just that i need
        to change "TARGET = bin" TO "TARGETDIR = bin"
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gordon-cs/Simulation-of-Metallic-Glass","title":"gordon-cs/Simulation-of-Metallic-Glass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gordon-cs/Simulation-of-Metallic-Glass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kuolu in #46: I figured it out and it's working now... It's just that i need to change \"TARGET = bin\" TO \"TARGETDIR = bin\""}],"action":{"name":"View Issue","url":"https://github.com/gordon-cs/Simulation-of-Metallic-Glass/issues/46#issuecomment-279822761"}}}
    
    
    -- 
      Jonathan R. Senning
      Professor of Mathematics and Computer Science
      Gordon College, 255 Grapevine Road, Wenham MA 01984-1899
      Voice: 978-867-4376, FAX: 978-867-4585
      Email: Jonathan.Senning@gordon.edu
      Web: http://www.math-cs.gordon.edu/~senning
